# Generated by Django 4.0.3 on 2023-08-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_tips_user_tips_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
