# Generated by Django 4.0.3 on 2023-08-02 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_pending_withdrawal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pending_withdrawal_currency',
        ),
        migrations.AlterField(
            model_name='user',
            name='pending_withdrawal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
