# Generated by Django 4.0.3 on 2023-08-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_pending_withdrawal_currency_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pending_withdrawal',
            new_name='pending_withdrawal_donations',
        ),
        migrations.AddField(
            model_name='user',
            name='pending_withdrawal_tips',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
