# Generated by Django 4.0.3 on 2023-06-23 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_user_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_tip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('application_for', models.CharField(max_length=255)),
                ('mode', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('mothers_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('marital_status', models.CharField(max_length=255)),
                ('specific_marital_status', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(null=True)),
                ('sex', models.CharField(max_length=255)),
                ('specific_sex', models.CharField(max_length=255)),
                ('blood_group', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=255)),
                ('identification_card', models.FileField(null=True, upload_to='post_documents/')),
                ('certificate_from_city_council', models.FileField(null=True, upload_to='post_documents/')),
                ('medical_report', models.FileField(null=True, upload_to='post_documents/')),
                ('permission_letter', models.FileField(null=True, upload_to='post_documents/')),
                ('test_results', models.FileField(null=True, upload_to='post_documents/')),
                ('name_of_employment', models.CharField(max_length=255)),
                ('photo', models.FileField(null=True, upload_to='post_documents/')),
                ('other_documents', models.FileField(null=True, upload_to='post_documents/')),
                ('live_description', models.FileField(null=True, upload_to='post_documents/')),
                ('written_description', models.TextField()),
                ('time_limit', models.CharField(max_length=255)),
                ('fixed_time', models.DateTimeField(null=True)),
                ('donation_needed', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raised', models.ManyToManyField(related_name='post_donations', through='gd.Donation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gd.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='tips',
            field=models.ManyToManyField(related_name='post_tips', through='gd.Tip', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gd.post'),
        ),
        migrations.AddField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gd.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
