# Generated by Django 4.0.3 on 2023-06-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0002_post_created_at_alter_post_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fixed_tip',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
