# Generated by Django 4.0.3 on 2023-06-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0003_alter_post_fixed_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], default='pending', max_length=255),
        ),
    ]
