# Generated by Django 4.0.3 on 2023-06-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0004_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
