# Generated by Django 4.0.3 on 2023-06-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0006_post_comments_post_total_donations_post_total_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tip',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
