# Generated by Django 4.0.3 on 2023-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0009_alter_post_fixed_tip_alter_post_fixed_tip_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='fixed_tip',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fixed_tip_currency',
        ),
        migrations.AddField(
            model_name='post',
            name='suggested_donations',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='suggested_tips',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
