# Generated by Django 4.0.3 on 2023-08-02 11:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0012_remove_post_suggested_tips_remove_post_total_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
