# Generated by Django 4.0.3 on 2023-08-02 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0013_donation_created_at_tip_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tip',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
