# Generated by Django 4.0.3 on 2023-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gd', '0014_alter_donation_created_at_alter_tip_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='credential_photos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
