# Generated by Django 4.0.3 on 2023-06-17 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_avatar_alter_user_billing_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place_of_birth',
        ),
    ]
