# Generated by Django 4.0.3 on 2023-08-05 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ce', '0004_rename_photo_template_cover_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
