# Generated by Django 4.0.3 on 2023-06-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0002_alter_order_date_alter_order_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('submitted', 'Submitted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
