# Generated by Django 4.0.3 on 2023-06-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
