# Generated by Django 4.0.3 on 2023-06-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0006_order_additional_file_order_address_order_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
