# Generated by Django 4.0.3 on 2023-07-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0009_alter_order_user_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_file',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='design_file',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_file',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
