# Generated by Django 4.0.3 on 2023-08-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0010_alter_order_additional_file_alter_order_design_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('short_description', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
