# Generated by Django 4.0.3 on 2023-08-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0013_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_title', models.CharField(max_length=100)),
                ('box_photo', models.CharField(max_length=10000)),
                ('box_description', models.TextField()),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('keywords', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
    ]
