# Generated by Django 4.0.3 on 2023-08-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0014_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='keywords',
            field=models.TextField(),
        ),
    ]
