# Generated by Django 4.0.3 on 2023-08-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0017_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
