# Generated by Django 4.0.3 on 2023-08-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0021_paymentoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('short_description', models.TextField()),
                ('keywords', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
