# Generated by Django 4.0.3 on 2023-08-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it', '0022_footerpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('short_description', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
    ]
